## 创建数组

In [2]:
import numpy as np

In [3]:
array1 = np.array([3,5,8])
arr2 = np.array([[5,55,6],[5,5.8,9]])
array1
arr2

array([[ 5. , 55. ,  6. ],
       [ 5. ,  5.8,  9. ]])

In [4]:
array1

array([3, 5, 8])

In [5]:
array1
arr2

array([[ 5. , 55. ,  6. ],
       [ 5. ,  5.8,  9. ]])

In [6]:
print(arr2.shape)
print(arr2.ndim)
print(arr2.dtype)

(2, 3)
2
float64


In [7]:
arr3=np.arange(0,10)
arr4 = np.arange(10)
arr5 =np.arange(0,1,0.1)
print(arr3)
print(arr4)
print(arr5)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [8]:
name = "wupeiqi"
new_name = name

name = "alex"
print(name)
print(new_name)

alex
wupeiqi


In [9]:
help(np.arange)

Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None, *, like=None)
    
    Return evenly spaced values within a given interval.
    
    ``arange`` can be called with a varying number of positional arguments:
    
    * ``arange(stop)``: Values are generated within the half-open interval
      ``[0, stop)`` (in other words, the interval including `start` but
      excluding `stop`).
    * ``arange(start, stop)``: Values are generated within the half-open
      interval ``[start, stop)``.
    * ``arange(start, stop, step)`` Values are generated within the half-open
      interval ``[start, stop)``, with spacing between values given by
      ``step``.
    
    For integer arguments the function is roughly equivalent to the Python
    built-in :py:class:`range`, but returns an ndarray rather than a ``range``
    instance.
    
    When using a non-integer step, such as 0.1, it is often better to use
    `numpy.linspace`.
    
    S

In [10]:
arr6 = np.linspace(0,1,11)

In [11]:
print(arr6)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [12]:
arr7=np.zeros([3,4,5])
print(arr7)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [13]:
arr8=np.array([1,5,4],dtype = np.float64)
arr9 = np.array([1,4.5,4])
print(arr8.dtype)
print(np.int32(arr9))
print(type(arr8))

float64
[1 4 4]
<class 'numpy.ndarray'>


In [14]:
print(np.random.random(10))
print(np.random.rand(3,4))#random的别名，早期形式（现已弃用）
print(np.random.randn(2,3,4))

[0.11437417 0.52549964 0.43345758 0.89194303 0.21809007 0.54792222
 0.20117879 0.76159023 0.3663948  0.94869918]
[[0.23316959 0.31868149 0.63180491 0.21871104]
 [0.36070849 0.92882698 0.54336429 0.98848615]
 [0.57418953 0.42639919 0.713028   0.14941817]]
[[[ 1.89088561 -0.94448274 -0.01279793 -1.32609315]
  [-1.25007593  0.5271057   0.65952951 -1.42363612]
  [-0.78848203 -0.69708369 -0.16843561  0.79442961]]

 [[ 0.80430204 -0.7511215   1.21321982  0.82973162]
  [ 1.71336456  1.26199755  0.95288257  0.22905614]
  [-0.68561816 -0.13110983  0.29604254 -0.74316748]]]


In [16]:
arrr1 = np.array([1,2.3,3.5,6.5,4.3])
print(arrr1)

[1.  2.3 3.5 6.5 4.3]


In [20]:
res1=arrr1[2]
res2=arrr1[2:3]
print(res1,res1.shape)
print(res2,res2.shape)

3.5 ()
[3.5] (1,)


In [26]:
ar2=np.array([1.8,0,5])
print(ar2[[True,True,True]])
print(ar2[[False,False,False]])

index = ar2>1#留下大于1的元素+
print(ar2[index])

[1.8 0.  5. ]
[]
[1.8 5. ]


In [32]:
ar3=np.arange(1,13).reshape([3,4])
print(ar3)
print(ar3[:,0])
print(ar3[0:,0])
print(ar3[ar3[:,0]>4,:])#对第一列中的每一个元素进行比较，检查它是否大于4。这会返回一个布尔数组，
#其长度与 `ar3` 的行数相同。数组中的每个元素都是 `True` 或 `False`，表示对应行的第一列元素是否大于4。

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[1 5 9]
[1 5 9]
[[ 5  6  7  8]
 [ 9 10 11 12]]


In [38]:
#求解距离矩阵
n = 3
x=np.linspace(0,100,n)
y=np.linspace(0,100,n)

dist = np.zeros([n,n])

for i in range(n):
    for j in range(n):
        dist[i,j]=np.sqrt((x[i]-x[j])**2+(y[i]-y[j])**2)
      
print(x)
print(y)
print(dist)

[  0.  50. 100.]
[  0.  50. 100.]
[[  0.          70.71067812 141.42135624]
 [ 70.71067812   0.          70.71067812]
 [141.42135624  70.71067812   0.        ]]


In [45]:
#数组形态变化
ar4=np.arange(1,13).reshape([3,4])
print(ar4)
print(ar4.ravel())#返回视图
print(ar4.flatten('F'))#返回副本

ar5 = np.arange(4,12).reshape([2,4])
print(ar5)

print(np.vstack((ar4,ar5))) #纵向，返回的是原始输入数组的垂直堆叠的副本，而不是视图

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  5  9  2  6 10  3  7 11  4  8 12]
[[ 4  5  6  7]
 [ 8  9 10 11]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [52]:
matr1=np.mat("1 2 3;4 5 6;7 8 9")#不建议使用，新版都用array
matr2=np.matrix([[1,2,3],[4,5,6],[7,8,8]])

matr3=np.bmat("matr1;matr2")

print(matr1)
print(matr2)
print(matr3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 8]]
[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]
 [4 5 6]
 [7 8 8]]


In [60]:
ars1=np.arange(1,13).reshape([3,4])
ars2=np.arange(1,13).reshape([4,3])

np.save('temp/ars1.npy',ars1)
ars1_load=np.load('temp/ars1.npy')
print(ars1_load)

np.savez('temp/ars1&2.npz',ars1,ars2)
ars2_load=np.load('temp/ars1&2.npz')

print(ars2_load)
print(ars2_load.files)
print(ars2_load['arr_0'])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
NpzFile 'temp/ars1&2.npz' with keys: arr_0, arr_1
['arr_0', 'arr_1']
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [61]:
np.savetxt('temp/ars_1',ars1,delimiter=",")
np.loadtxt('temp/ars_1',delimiter=",")

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

In [6]:
import numpy as np
ara1 = np.random.randint(1,10,(3,3))
print(ara1)
ara1.sort(axis=0)
print(ara1)
print(ara1.argsort(axis=0))

[[2 8 4]
 [1 1 9]
 [7 9 3]]
[[1 1 3]
 [2 8 4]
 [7 9 9]]
[[0 0 0]
 [1 1 1]
 [2 2 2]]


In [8]:
print(np.tile(ara1,2))
print(np.repeat(ara1,2,axis = 1))

[[1 1 3 1 1 3]
 [2 8 4 2 8 4]
 [7 9 9 7 9 9]]
[[1 1 1 1 3 3]
 [2 2 8 8 4 4]
 [7 7 9 9 9 9]]


In [21]:
print(ara1.mean())
print(np.mean(ara1,axis=1))#print(ara1.mean(axis=1))
print(ara1.max(axis=1))
print(ara1.argmax(axis=1))

4.888888888888889
[1.66666667 4.66666667 8.33333333]
[3 8 9]
[2 1 1]
